# Site settings
title: Sorrento Meeting
subtitle: The Future of ML Publishing
permalink: "/:title.html"
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the Sorrento Meeting 2026.
baseurl: "/sorrento2026" # the subpath of your site, e.g. /blog/

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username:

github_username: lawrennd
repository: lawrennd/sorrento2026

author:
  name: Sorrento Meeting
  # You might want to create an email for handling conference queries, e.g. aistats20XX@gmail.com. If you do, you can enter it here.
  email: chc73@cam.ac.uk
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
exclude:
- doc
- vendor
- vendor/bundle
- .bundle
- Gemfile
- Gemfile.lock
remote_theme: cabrerac/jekyll-theme-sorrento
style: sorrento

ghub:
  edit: true
  repository: sorrento2026

# Also generate pages with dates in the future
future: true

# Place a banner image in assets/images and give its name here.
banner: sorrento.png

conference:
  draft: false
  hide_tentative: false
  full_name: Sorrento Meeting
  short_name: Sorrento 2026
  name: The Sorrento Meeting
  # set to True to hide tentative speakers
  hide_tentative: true
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  #proceedings:
    # When proceedings are published add url here.
    #url:
    #show: false
  # Give details of the room in the venue here.
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)
  venue: Grand Hotel Vesuvio
  # Give the url of the venue here.
  venue_url: https://www.vesuviosorrento.com/
  # Give the conference location in the form City, Country here.
  location: Sorrento, Italy
  year: 2026
  # Give the instance of the conference here (e.g. 24th)
  instance:
  # Styling for DALI is "Workshop on"
  #styling: Workshop on
  # Give the individual days that the conference will be held on here.
  dates:
  - 2026-03-30
  - 2026-03-31
  - 2026-04-01
  # Give the submission site details here.
  #submission:
    # Whether to show the submission site.
    #show: false
    # The URL of the submission site.
    #url:
    # The name of the submission site (e.g. Microsoft CMT Website)
    #name:
  #deadlines:
    # Fill in the key dates as below.
    #- name: Submission server open
    #  type: submission
    #  ate:
    #- name: Paper submission deadline
    #  type: submission
    #  time: 2024-10-11
    #- name: Author response period starts
    #  date:
    #- name: Author response period ends
    #  time:
    #- name: Paper decision notifications
    #  date: 2024-10-18
    #  type: decision
    #- name: Deadline for camera-ready papers
    #  time:
    #- name: Registration deadline
    #  date:
  # List program chairs here.
  chairs:
  - type: General Chairs
    people:
    - family: Lawrence
      given: Neil D.
      # Give their personal web page.
      url: https://inverseprobability.com
      institute: University of Cambridge
    - family: Sondermann
      given: Hanni
      url: https://www.cst.cam.ac.uk/people/hes24
      institute: University of Cambridge
    - family: Provost
      given: Bianca
      url: https://www.cst.cam.ac.uk/people/bp374
      institute: University of Cambridge
    - family: Finley
      given: Griffin
      url: https://www.cst.cam.ac.uk/people/flsg2
      institute: University of Cambridge
    - family: Sendyka
      given: Radzim
      url: https://science.ai.cam.ac.uk/team/radzim-sendyka
      institute: University of Cambridge
    - family: Cabrera-Jojoa
      given: Christian
      url: https://cabrerac.github.io/
      institute: University of Cambridge
  - type: Steering Committee
    people:
    - given: Neil D.
      family: Lawrence
      url: "http://inverseprobability.com"
      institute: University of Cambridge
    - given: Jessica
      family: Montgomery
      url: https://www.ai.cam.ac.uk/people/jess-montgomery/
      institute: University of Cambridge

