# Site settings
title: The Sorrento Meeting 2026
subtitle: The Future of ML Publishing
permalink: "/:title.html"
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the Sorrento Meeting 2026.
baseurl: "/sorrento2026" # the subpath of your site, e.g. /blog/

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username:

github_username:  lawrennd

author:
  name: Sorrento Meeting
  # You might want to create an email for handling conference queries, e.g. aistats20XX@gmail.com. If you do, you can enter it here.
  email:
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
exclude: doc
remote_theme: lawrennd/jekyll-theme
style: dali

ghub:
  edit: true
  repository: sorrento2026

# Also generate pages with dates in the future
future: true

# Place a banner image in assets/images and give its name here.
banner: sorrento.png

conference:
  draft: false
  hide_tentative: false
  full_name: The Sorrento Meeting
  short_name: Sorrento 2026
  name: The Sorrento Meeting
  # set to True to hide tentative speakers
  hide_tentative: true
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  proceedings:
    # When proceedings are published add url here.
    url:
    show: false
  # Give details of the room in the venue here.
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)
  venue: Grand Hotel Vesuvio
  # Give the url of the venue here.
  venue_url: https://www.vesuviosorrento.com/
  # Give the conference location in the form City, Country here.
  location: Sorrento, Italy
  year: 2026
  # Give the instance of the conference here (e.g. 24th)
  instance:
  # Styling for DALI is "Workshop on"
  #styling: Workshop on
  # Give the individual days that the conference will be held on here.
  dates:
  - 30/03/2026
  - 31/03/2026
  - 01/04/2026
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: false
    # The URL of the submission site.
    url:
    # The name of the submission site (e.g. Microsoft CMT Website)
    name:
  deadlines:
    # Fill in the key dates as below.
    - name: Submission server open
      type: submission
      date:
    - name: Paper submission deadline
      type: submission
      time: 2024-10-11
    - name: Author response period starts
      date:
    - name: Author response period ends
      time:
    - name: Paper decision notifications
      date: 2024-10-18
      type: decision
    - name: Deadline for camera-ready papers
      time:
    - name: Registration deadline
      date:
  # List program chairs here.
  chairs:
  - type: General Chairs
    people:
    - family: Lawrence
      given: Neil D.
      # Give their personal web page.
      url: https://inverseprobability.com
      institute: University of Cambridge
    - family: Sondermann
      given: Hanni
      institute: University of Cambridge
    - family: Provist
      given: Bianca
      institute: University of Cambridge
    - family: Cabrera-Jojoa
      given: Christian
      url: https://cabrerac.github.io/
      institute: University of Cambridge
  - type: Steering Committee
    people:
    - given: Neil D.
      family: Lawrence
      url: "http://inverseprobability.com"
      institute: University of Cambridge
